#!/bin/bash

# This file was generated by chatGPT

SSL_DIR="$HOME/.custom_vpn/ssl/ca"

# 1. Create the directory if it doesn't exist
if [ ! -d "$SSL_DIR" ]; then
  mkdir -p "$SSL_DIR"
  echo "Created directory: $SSL_DIR"
fi

# 2. Define env vars
ENV_VARS=$(cat <<EOF

# >>> custom_vpn ENV START >>>
export SERVER_PEM="$SSL_DIR/server.pem"
export SERVER_KEY="$SSL_DIR/server.key"
export CA_CERT_LOC="$SSL_DIR/ca/ca.pem"
# <<< custom_vpn ENV END <<<
EOF
)

# 3. Ensure block isn't duplicated
if ! grep -q "custom_vpn ENV START" "$HOME/.bashrc"; then
  echo "$ENV_VARS" >> "$HOME/.bashrc"
  echo "Environment variables added to ~/.bashrc"
else
  echo "Environment variables already present in ~/.bashrc"
fi

# 4. Ensure .bash_profile sources .bashrc (macOS / login shells)
if [ -f "$HOME/.bash_profile" ]; then
  if ! grep -q 'source ~/.bashrc' "$HOME/.bash_profile"; then
    echo 'source ~/.bashrc' >> "$HOME/.bash_profile"
    echo "Ensured .bash_profile sources .bashrc"
  fi
else
  echo 'source ~/.bashrc' > "$HOME/.bash_profile"
  echo "Created .bash_profile and linked it to .bashrc"
fi

echo "Setup complete. Open a new terminal or run: source ~/.bashrc"